version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: "ToDoList"
      MYSQL_USER: "ToDoList_user"
      MYSQL_PASSWORD: "ToDoList_password"
      MYSQL_ROOT_PASSWORD: "AhmedAmin@82253"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_net

  web:
    build: .
    container_name: todo_app
    command: python3.11 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - todo_net

networks:
  todo_net:

volumes:
  db_data:
